apiVersion: v1
kind: ReplicationController
metadata: # this is for replication controller
  name: nginx-rc
  labels:
    env: demo
spec:  # spec for replication controller
  template: # this is pod template
    metadata: # this is for pod
      labels:
        env:  demo
      name: nginx
    spec: #spec for pod
      containers:
      - image: nginx
        name: nginx
  repicas: 3
    
